/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MarkCreator {
    }
    interface MarkEditor {
    }
    interface MarkPhotos {
        "getImages": () => Promise<Map<string, File>>;
        "load": (file: File) => Promise<void>;
    }
}
export interface MarkEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMarkEditorElement;
}
declare global {
    interface HTMLMarkCreatorElement extends Components.MarkCreator, HTMLStencilElement {
    }
    var HTMLMarkCreatorElement: {
        prototype: HTMLMarkCreatorElement;
        new (): HTMLMarkCreatorElement;
    };
    interface HTMLMarkEditorElementEventMap {
        "markContentUpdate": string;
    }
    interface HTMLMarkEditorElement extends Components.MarkEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMarkEditorElementEventMap>(type: K, listener: (this: HTMLMarkEditorElement, ev: MarkEditorCustomEvent<HTMLMarkEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMarkEditorElementEventMap>(type: K, listener: (this: HTMLMarkEditorElement, ev: MarkEditorCustomEvent<HTMLMarkEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMarkEditorElement: {
        prototype: HTMLMarkEditorElement;
        new (): HTMLMarkEditorElement;
    };
    interface HTMLMarkPhotosElement extends Components.MarkPhotos, HTMLStencilElement {
    }
    var HTMLMarkPhotosElement: {
        prototype: HTMLMarkPhotosElement;
        new (): HTMLMarkPhotosElement;
    };
    interface HTMLElementTagNameMap {
        "mark-creator": HTMLMarkCreatorElement;
        "mark-editor": HTMLMarkEditorElement;
        "mark-photos": HTMLMarkPhotosElement;
    }
}
declare namespace LocalJSX {
    interface MarkCreator {
    }
    interface MarkEditor {
        "onMarkContentUpdate"?: (event: MarkEditorCustomEvent<string>) => void;
    }
    interface MarkPhotos {
    }
    interface IntrinsicElements {
        "mark-creator": MarkCreator;
        "mark-editor": MarkEditor;
        "mark-photos": MarkPhotos;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mark-creator": LocalJSX.MarkCreator & JSXBase.HTMLAttributes<HTMLMarkCreatorElement>;
            "mark-editor": LocalJSX.MarkEditor & JSXBase.HTMLAttributes<HTMLMarkEditorElement>;
            "mark-photos": LocalJSX.MarkPhotos & JSXBase.HTMLAttributes<HTMLMarkPhotosElement>;
        }
    }
}
