/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MarkEditor {
    }
}
declare global {
    interface HTMLMarkEditorElement extends Components.MarkEditor, HTMLStencilElement {
    }
    var HTMLMarkEditorElement: {
        prototype: HTMLMarkEditorElement;
        new (): HTMLMarkEditorElement;
    };
    interface HTMLElementTagNameMap {
        "mark-editor": HTMLMarkEditorElement;
    }
}
declare namespace LocalJSX {
    interface MarkEditor {
    }
    interface IntrinsicElements {
        "mark-editor": MarkEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mark-editor": LocalJSX.MarkEditor & JSXBase.HTMLAttributes<HTMLMarkEditorElement>;
        }
    }
}
